services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - APP_URL=http://localhost:3000
      - CREDIT_SCORING_URL=http://credit_scoring:5001
      - GMAIL_USER=usmproyecto00@gmail.com
      - GMAIL_PASS=oxlneinezrytulkd
      - TWILIO_ACCOUNT_SID=YOUR_TWILIO_SID
      - TWILIO_AUTH_TOKEN=YOUR_TWILIO_TOKEN
      - TWILIO_WHATSAPP_FROM=+14155238886
      - TWILIO_SMS_FROM=+12183576951
    depends_on:
      - postgres_db
      - credit_scoring
    volumes:
      - .:/app:cached
      - /app/node_modules

  credit_scoring:
    build: 
      context: ./credit-scoring-service
      network: host
    ports:
      - "5001:5001"
    volumes:
      - ./credit_model.pkl:/app/credit_model.pkl:ro
      - ./model_metadata.json:/app/model_metadata.json:ro

  postgres_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data:
